// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {media} from '../models';
import {engine} from '../models';
import {store} from '../models';

export function AddDroppedFiles(arg1:Array<string>):Promise<main.AddResult>;

export function AddFilesDialog(arg1:boolean):Promise<main.AddResult>;

export function AddFolderDialog(arg1:boolean):Promise<main.AddResult>;

export function AddPaths(arg1:Array<string>,arg2:boolean):Promise<main.AddResult>;

export function AppVersion():Promise<string>;

export function AutoDetectBinaries():Promise<media.Binaries>;

export function Binaries():Promise<media.Binaries>;

export function Bootstrap():Promise<main.Bootstrap>;

export function CheckBinary(arg1:string):Promise<media.ToolInfo>;

export function ClearHistory():Promise<void>;

export function ClearQueue():Promise<number>;

export function DataDir():Promise<string>;

export function DeleteOutput(arg1:string):Promise<engine.DeleteResult>;

export function DeleteOutputs(arg1:Array<string>):Promise<engine.DeleteResult>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DetectEncoders():Promise<Array<main.EncoderSupport>>;

export function DuplicateTemplate(arg1:string):Promise<store.Template>;

export function ExportHistoryCSV(arg1:main.HistoryQuery):Promise<string>;

export function ExportTemplates():Promise<string>;

export function GlobalTemplate():Promise<store.Template>;

export function History(arg1:main.HistoryQuery):Promise<main.HistoryPage>;

export function ImportTemplatesFromFile():Promise<number>;

export function JobLogs(arg1:string):Promise<Array<string>>;

export function Jobs():Promise<Array<engine.Job>>;

export function NewTemplate():Promise<store.Template>;

export function OpenOutputDir():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PauseQueue():Promise<void>;

export function PickBinary():Promise<string>;

export function PickDirectory():Promise<string>;

export function PreviewCommand(arg1:string,arg2:string):Promise<engine.Plan>;

export function PreviewTemplate(arg1:store.Template,arg2:string):Promise<engine.Plan>;

export function Probe(arg1:string):Promise<media.Info>;

export function Quit():Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveFinished():Promise<number>;

export function RemoveJob(arg1:string):Promise<void>;

export function RemoveJobs(arg1:Array<string>):Promise<number>;

export function ReorderTemplates(arg1:Array<string>):Promise<Array<store.Template>>;

export function ResetSettings():Promise<store.Settings>;

export function ResumeQueue():Promise<void>;

export function RetryFailed():Promise<number>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveGlobalTemplate(arg1:store.Template):Promise<store.Template>;

export function SaveSettings(arg1:store.Settings):Promise<store.Settings>;

export function SaveTemplate(arg1:store.Template):Promise<store.Template>;

export function SetAllTemplates(arg1:string):Promise<engine.ApplyResult>;

export function SetJobTemplate(arg1:string,arg2:string):Promise<void>;

export function Settings():Promise<store.Settings>;

export function ShowDataDir():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartQueue():Promise<void>;

export function Stats():Promise<engine.Stats>;

export function StopQueue():Promise<void>;

export function Templates():Promise<Array<store.Template>>;

export function TogglePause():Promise<boolean>;

export function ToolInfo():Promise<media.ToolInfo|media.ToolInfo>;
