// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDroppedFiles(arg1) {
  return window['go']['main']['App']['AddDroppedFiles'](arg1);
}

export function AddFilesDialog(arg1) {
  return window['go']['main']['App']['AddFilesDialog'](arg1);
}

export function AddFolderDialog(arg1) {
  return window['go']['main']['App']['AddFolderDialog'](arg1);
}

export function AddPaths(arg1, arg2) {
  return window['go']['main']['App']['AddPaths'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AutoDetectBinaries() {
  return window['go']['main']['App']['AutoDetectBinaries']();
}

export function Binaries() {
  return window['go']['main']['App']['Binaries']();
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckBinary(arg1) {
  return window['go']['main']['App']['CheckBinary'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearQueue() {
  return window['go']['main']['App']['ClearQueue']();
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function DeleteFilterProfile(arg1) {
  return window['go']['main']['App']['DeleteFilterProfile'](arg1);
}

export function DeleteFilterProfiles(arg1) {
  return window['go']['main']['App']['DeleteFilterProfiles'](arg1);
}

export function DeleteOutput(arg1) {
  return window['go']['main']['App']['DeleteOutput'](arg1);
}

export function DeleteOutputs(arg1) {
  return window['go']['main']['App']['DeleteOutputs'](arg1);
}

export function DeleteRecords(arg1) {
  return window['go']['main']['App']['DeleteRecords'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DeleteTemplates(arg1) {
  return window['go']['main']['App']['DeleteTemplates'](arg1);
}

export function DetectEncoders() {
  return window['go']['main']['App']['DetectEncoders']();
}

export function DuplicateTemplate(arg1) {
  return window['go']['main']['App']['DuplicateTemplate'](arg1);
}

export function ExportHistoryCSV(arg1) {
  return window['go']['main']['App']['ExportHistoryCSV'](arg1);
}

export function ExportTemplates() {
  return window['go']['main']['App']['ExportTemplates']();
}

export function FilterState() {
  return window['go']['main']['App']['FilterState']();
}

export function GlobalTemplate() {
  return window['go']['main']['App']['GlobalTemplate']();
}

export function History(arg1) {
  return window['go']['main']['App']['History'](arg1);
}

export function ImportTemplatesFromFile() {
  return window['go']['main']['App']['ImportTemplatesFromFile']();
}

export function JobLogs(arg1) {
  return window['go']['main']['App']['JobLogs'](arg1);
}

export function Jobs() {
  return window['go']['main']['App']['Jobs']();
}

export function Locate(arg1, arg2) {
  return window['go']['main']['App']['Locate'](arg1, arg2);
}

export function NewTemplate() {
  return window['go']['main']['App']['NewTemplate']();
}

export function OpenOutputDir() {
  return window['go']['main']['App']['OpenOutputDir']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function PickBinary() {
  return window['go']['main']['App']['PickBinary']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PreviewCommand(arg1, arg2) {
  return window['go']['main']['App']['PreviewCommand'](arg1, arg2);
}

export function PreviewFolderScan(arg1) {
  return window['go']['main']['App']['PreviewFolderScan'](arg1);
}

export function PreviewPaths(arg1, arg2) {
  return window['go']['main']['App']['PreviewPaths'](arg1, arg2);
}

export function PreviewTemplate(arg1, arg2) {
  return window['go']['main']['App']['PreviewTemplate'](arg1, arg2);
}

export function Probe(arg1) {
  return window['go']['main']['App']['Probe'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveFinished() {
  return window['go']['main']['App']['RemoveFinished']();
}

export function RemoveJob(arg1) {
  return window['go']['main']['App']['RemoveJob'](arg1);
}

export function RemoveJobs(arg1) {
  return window['go']['main']['App']['RemoveJobs'](arg1);
}

export function ReorderTemplates(arg1) {
  return window['go']['main']['App']['ReorderTemplates'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function ResumeQueue() {
  return window['go']['main']['App']['ResumeQueue']();
}

export function RetryFailed() {
  return window['go']['main']['App']['RetryFailed']();
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function SaveFilterProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveFilterProfile'](arg1, arg2);
}

export function SaveGlobalTemplate(arg1) {
  return window['go']['main']['App']['SaveGlobalTemplate'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SetActiveFilter(arg1, arg2) {
  return window['go']['main']['App']['SetActiveFilter'](arg1, arg2);
}

export function SetAllTemplates(arg1) {
  return window['go']['main']['App']['SetAllTemplates'](arg1);
}

export function SetJobTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetJobTemplate'](arg1, arg2);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function ShowDataDir() {
  return window['go']['main']['App']['ShowDataDir']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartQueue() {
  return window['go']['main']['App']['StartQueue']();
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function StopQueue() {
  return window['go']['main']['App']['StopQueue']();
}

export function Templates() {
  return window['go']['main']['App']['Templates']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function ToolInfo() {
  return window['go']['main']['App']['ToolInfo']();
}
